/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JInternalFrame;

import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory.Default;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratham
 */
public class Fines extends javax.swing.JInternalFrame {

    /**
     * Creates new form Fines
     */
    public Fines() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        scrollbar1 = new java.awt.Scrollbar();

        setPreferredSize(new java.awt.Dimension(1166, 1000));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Fines");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("Refresh/Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Paid And Unpaid Fines");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jRadioButton2.setText("Unpaid Fines ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton3.setText("Pay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jRadioButton3.setText("Only Unpaid Fines (Read-Only)");
        jRadioButton3.setMinimumSize(new java.awt.Dimension(191, 21));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jRadioButton4.setText("Only Paid Fines");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jRadioButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(304, 304, 304)
                                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                                .addComponent(scrollbar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(scrollbar1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static PreparedStatement Stmt = null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            jTable1.setModel(new DefaultTableModel());
            jTable2.setModel(new DefaultTableModel());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/library","root","Pratham@88");
              if(jRadioButton1.isSelected())
                { 
                    
                  Stmt= con.prepareStatement("Select bl.book_id,bl.branch_id,bl.card_no,bl.date_out,bl.date_due,bl.date_in,sum(f.fine_amt),f.paid from book_loans bl, fines f where bl.loan_id = f.loan_id Group By card_no");
                  ResultSet rs = Stmt.executeQuery();
                  
                   ResultSetMetaData rsmd=rs.getMetaData();
                     int columns = rsmd.getColumnCount();
                     DefaultTableModel model = new DefaultTableModel();
                     Vector columnname= new Vector();
                     Vector datarows = new Vector ();
                               
                               for(int i=1;i<=columns;i++)
                                 {
                                           columnname.addElement(rsmd.getColumnName(i));                           
                                  }
                               model.setColumnIdentifiers(columnname);
                               
                               while(rs.next())
                               {
                                      datarows = new Vector();
                                      for(int j=1; j<= columns;j++)
                                       {
                                             datarows.addElement(rs.getString(j));
                                       }        
                                      model.addRow(datarows);
                                      jTable1.setModel(model);
                                }
                }
            else if(jRadioButton2.isSelected())
            {
                 Stmt= con.prepareStatement("Select bl.loan_id,bl.book_id,bl.branch_id,bl.card_no,bl.date_out,bl.date_due,bl.date_in,sum(f.fine_amt),f.paid from fines f, book_loans bl where bl.loan_id = f.loan_id AND f.paid = 0 and bl.date_in is not null Group By bl.card_no");
                  ResultSet rs = Stmt.executeQuery();
                  
                   ResultSetMetaData rsmd=rs.getMetaData();
                     int columns = rsmd.getColumnCount();
                     DefaultTableModel model = new DefaultTableModel();
                     Vector columnname= new Vector();
                     Vector datarows = new Vector ();
                               
                               for(int i=1;i<=columns;i++)
                                 {
                                           columnname.addElement(rsmd.getColumnName(i));                           
                                  }
                               model.setColumnIdentifiers(columnname);
                               
                               while(rs.next())
                               {
                                      datarows = new Vector();
                                      for(int j=1; j<= columns;j++)
                                       {
                                             datarows.addElement(rs.getString(j));
                                       }        
                                      model.addRow(datarows);
                                      jTable2.setModel(model);
                                }

            }
               else if(jRadioButton3.isSelected())
            {
            Stmt= con.prepareStatement("Select bl.book_id,bl.branch_id,bl.card_no,bl.date_out,bl.date_due,bl.date_in,sum(f.fine_amt),f.paid from book_loans bl, Fines f where bl.loan_id = f.loan_id AND f.paid = 0 Group By bl.card_no");
                  ResultSet rs = Stmt.executeQuery();
                  
                   ResultSetMetaData rsmd=rs.getMetaData();
                     int columns = rsmd.getColumnCount();
                     DefaultTableModel model = new DefaultTableModel(){ public boolean isCellEditable(int row, int column){return false;}};
                    jTable4.setEnabled(false);
                     Vector columnname= new Vector();
                     Vector datarows = new Vector ();
                               
                               for(int i=1;i<=columns;i++)
                                 {
                                           columnname.addElement(rsmd.getColumnName(i));                           
                                  }
                               model.setColumnIdentifiers(columnname);
                               
                               while(rs.next())
                               {
                                      datarows = new Vector();
                                      for(int j=1; j<= columns;j++)
                                       {
                                             datarows.addElement(rs.getString(j));
                                       }        
                                      model.addRow(datarows);
                                      jTable4.setModel(model);
                                }

            }
               else if(jRadioButton4.isSelected())
            {
            Stmt= con.prepareStatement("Select bl.book_id,bl.branch_id,bl.card_no,bl.date_out,bl.date_due,bl.date_in,sum(f.fine_amt),f.paid from book_loans bl, Fines f where bl.loan_id = f.loan_id AND f.paid = 1 Group by bl.card_no");
                  ResultSet rs = Stmt.executeQuery();
                  
                   ResultSetMetaData rsmd=rs.getMetaData();
                     int columns = rsmd.getColumnCount();
                     DefaultTableModel model = new DefaultTableModel();
                     Vector columnname= new Vector();
                     Vector datarows = new Vector ();
                               
                               for(int i=1;i<=columns;i++)
                                 {
                                           columnname.addElement(rsmd.getColumnName(i));                           
                                  }
                               model.setColumnIdentifiers(columnname);
                               
                               while(rs.next())
                               {
                                      datarows = new Vector();
                                      for(int j=1; j<= columns;j++)
                                       {
                                             datarows.addElement(rs.getString(j));
                                       }        
                                      model.addRow(datarows);
                                      jTable2.setModel(model);
                                }

            } 
                
        } 
                
        catch(Exception e)
        {
         e.printStackTrace();
        }
        
                   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          int       selectedRowIndex = jTable2.getSelectedRow();
                     System.out.println("hello");
                     System.out.println(selectedRowIndex);
                     if(selectedRowIndex == -1)  
                        {
                           
                            JFrame frame =new JFrame();
                            JOptionPane.showMessageDialog(frame,"Select atleast one entry");  
                         }
                        
                      else
                        {
                            
                        Object loan_id;
                       
                        
                        
                        
              try{
                  
                  // Create a connection to the local MySQL server, with the "library" database selected.
                        Connection con;
			con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library","root","Pratham@88");
                      
                                                         
                        
                            
                        
                         loan_id=jTable2.getValueAt(selectedRowIndex,0);
                         Stmt= con.prepareStatement("Update fines set paid=1 where loan_id="+loan_id+"");
                         Stmt.executeUpdate ();
                    
                        
                                       
  }
              catch(Exception e)
              {
                  
                e.printStackTrace();
        
              }
         }
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private java.awt.Scrollbar scrollbar1;
    // End of variables declaration//GEN-END:variables
}
