/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JInternalFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Pratham
 */
public class Main extends javax.swing.JFrame {
 public static PreparedStatement Stmt = null;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
    }
    
  
           
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        MenuItem1 = new javax.swing.JMenuItem();
        MenuItem2 = new javax.swing.JMenuItem();
        MenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpane.setInheritsPopupMenu(true);
        getContentPane().add(mainpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 1130, 640));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To Library");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 468, -1));

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        MenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        MenuItem1.setText("Search");
        MenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem1ActionPerformed(evt);
            }
        });
        Menu.add(MenuItem1);

        MenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        MenuItem2.setText("Book_Loans");
        MenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem2ActionPerformed(evt);
            }
        });
        Menu.add(MenuItem2);

        MenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        MenuItem3.setText("Add_Borrower");
        MenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem3ActionPerformed(evt);
            }
        });
        Menu.add(MenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Fines");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem1);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem2ActionPerformed
        Loans m1 = new Loans();
        mainpane.add(m1);
        m1.show(); 
    }//GEN-LAST:event_MenuItem2ActionPerformed

    private void MenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem3ActionPerformed
       Borrower m3=new Borrower();
        mainpane.add(m3);
        m3.show();
    }//GEN-LAST:event_MenuItem3ActionPerformed

    private void MenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem1ActionPerformed
        // TODO add your handling code here:
        Search m1 = new Search();
        mainpane.add(m1);
        m1.show();        
    }//GEN-LAST:event_MenuItem1ActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_MenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     try
     {
         Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/library","root","Pratham@88");
        Stmt = con.prepareStatement ("INSERT INTO fines SELECT bl.loan_id, 0.25*(datediff(curdate() ,bl.date_due)),0 FROM book_loans bl WHERE (datediff(curdate(),bl.date_out)) > 14 and date_in is null on duplicate key update fine_amt=0.25*(datediff(curdate(),bl.date_due))");
         Stmt.executeUpdate();
         Stmt = con.prepareStatement ("INSERT INTO fines SELECT bl.loan_id,(0.25*datediff(bl.date_in ,bl.date_due)),0 FROM book_loans bl WHERE (datediff(bl.date_in,bl.date_out))>14 on duplicate key update fine_amt=0.25*(datediff(bl.date_in,bl.date_due))");
         Stmt.executeUpdate();
        Fines m1 = new Fines();
        mainpane.add(m1);
        m1.show();
      }
       /* catch (ClassNotFoundException ex) {
         Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
     } */
     catch (Exception e) {
         e.printStackTrace();
     }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
             

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem MenuItem1;
    private javax.swing.JMenuItem MenuItem2;
    private javax.swing.JMenuItem MenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private static javax.swing.JDesktopPane mainpane;
    // End of variables declaration//GEN-END:variables
}
