/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package JInternalFrame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pratham
 */
public class Search extends javax.swing.JInternalFrame {
public static PreparedStatement Stmt = null;
    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SLabel1 = new javax.swing.JLabel();
        SLabel2 = new javax.swing.JLabel();
        SLabel3 = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        authorname = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        SLabel4 = new javax.swing.JLabel();
        SLabel5 = new javax.swing.JLabel();
        SLabel6 = new javax.swing.JLabel();
        bookid1 = new javax.swing.JTextField();
        authorname1 = new javax.swing.JTextField();
        title1 = new javax.swing.JTextField();
        reset1 = new javax.swing.JButton();
        search1 = new javax.swing.JButton();
        SLabel7 = new javax.swing.JLabel();
        authorname2 = new javax.swing.JTextField();
        SLabel8 = new javax.swing.JLabel();
        authorname3 = new javax.swing.JTextField();
        authorname4 = new javax.swing.JTextField();
        SLabel9 = new javax.swing.JLabel();
        RadioButton1 = new javax.swing.JRadioButton();
        RadioButton2 = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        SLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLabel1.setText("Book Id:");

        SLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLabel2.setText("Title:");

        SLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLabel3.setText("First Name:");

        bookid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookidActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        SLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLabel4.setText("Book Id:");

        SLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLabel5.setText("Title:");

        SLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLabel6.setText("Author Name:");

        bookid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookid1ActionPerformed(evt);
            }
        });

        reset1.setText("Reset");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });

        search1.setText("Search");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(reset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bookid1)
                            .addComponent(authorname1)
                            .addComponent(title1))
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(116, 116, 116))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookid1)
                    .addComponent(SLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(SLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(SLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(authorname1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
        );

        SLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLabel7.setText("Middle Name:");

        SLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLabel8.setText("Last Name:");

        authorname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorname4ActionPerformed(evt);
            }
        });

        SLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SLabel9.setText("Author Name:");

        buttonGroup1.add(RadioButton1);
        RadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        RadioButton1.setSelected(true);
        RadioButton1.setText("Search By Author Name");
        RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButton2);
        RadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        RadioButton2.setText("Search any or all ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(161, 161, 161)
                        .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorname4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(authorname3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(authorname, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(authorname2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RadioButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bookid, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                    .addComponent(title))
                                .addGap(112, 112, 112))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(RadioButton2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 303, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 303, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookid, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(SLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton2)
                    .addComponent(RadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(authorname4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(SLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(SLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(authorname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(authorname2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(authorname3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 191, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 191, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        bookid.setText("");
        title.setText("");
        authorname.setText("");
        authorname2.setText("");
        authorname3.setText("");
        authorname4.setText("");
        
    }//GEN-LAST:event_resetActionPerformed

    private void bookidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bookidActionPerformed
public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
      
      
}
    public static String id ,t,fname,minit,lname,author_name;
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
        try
        {
         Class.forName("com.mysql.jdbc.Driver");
         Connection con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/library","root","Pratham@88");
         id = bookid.getText();
         t = title.getText();
         author_name=authorname4.getText();
         fname = authorname.getText();
         minit = authorname2.getText();
         lname = authorname3.getText();
                  
             if(RadioButton1.isSelected())
            {
                if(id.equals("") && author_name.equals("") && t.equals(""))
                 {
                     JFrame frame = new JFrame();
                    JOptionPane.showMessageDialog(frame,"Enter At Least One Value");
                  }
                
                else    
                {
                 Stmt = con.prepareStatement ("Select bk.book_id,bk.title,ba.Author_Name,bc.Branch_id,bc.No_of_Copies,(bc.No_Of_Copies-(Count(bl.book_id))) As Available_Copies from book bk, book_authors ba, book_copies bc, book_loans bl where ba.author_name like '%"+author_name+"%' and bk.book_id like '%"+id+"%' AND bk.title like '%"+t+"%'  AND bk.book_id=ba.book_id AND bk.book_id=bc.book_id AND bk.book_id=bl.book_id AND bc.branch_id=bl.branch_id Group By bc.branch_id, ba.author_name Union Select bk.book_id,bk.title,ba.Author_Name,bc.Branch_id,bc.No_of_Copies,bc.No_Of_Copies As Available_Copies from book bk, book_authors ba, book_copie s bc where ba.author_name like '%"+author_name+"%'and bk.book_id like '%"+id+"%'AND bk.title like '%"+t+"%'AND bk.book_id=ba.book_id AND bk.book_id=bc.book_id AND bc.branch_id Not In (Select bl.branch_id from book_loans bl where bc.book_id=bl.book_id AND bc.branch_id = bl.branch_id and bl.date_in <=> null) order by title,branch_id");
                 ResultSet rs = Stmt.executeQuery();
                 Output o=new Output("njk");
                 o.display(rs);
                } 
            }
             else if (RadioButton2.isSelected())
             {
                if(id.equals("") && fname.equals("") && t.equals("") && lname.equals("") && minit.equals(""))
                 {
                     JFrame frame = new JFrame();
                    JOptionPane.showMessageDialog(frame,"Enter At Least One Value");
                  }
                else if(minit.equals(""))
                {
                 Stmt = con.prepareStatement ("(Select bk.book_id,bk.title,ba.Author_Name,bc.Branch_id,bc.No_of_Copies,(bc.No_Of_Copies-(Count(bl.book_id))) As Available_Copies from book bk, book_authors ba, book_copies bc, book_loans bl where  bk.book_id like '%"+id+"%' AND bk.title like '%"+t+"%' AND ba.fname like '%"+fname+"%' AND ba.lname like '%"+lname+"%' AND bk.book_id=ba.book_id AND bk.book_id=bc.book_id AND bk.book_id=bl.book_id AND bc.branch_id=bl.branch_id Group By bc.branch_id, ba.author_name)Union (Select bk.book_id,bk.title,ba.Author_Name,bc.Branch_id,bc.No_of_Copies,bc.No_Of_Copies As Available_Copies from book bk, book_authors ba, book_copies bc where ba.fname like '%"+fname+"%' AND ba.lname like '%"+lname+"%' AND bk.book_id like '%"+id+"%'AND bk.title like '%"+t+"%'AND bk.book_id=ba.book_id AND bk.book_id=bc.book_id AND bc.branch_id Not In (Select bl.branch_id from book_loans bl where bc.book_id=bl.book_id AND bc.branch_id = bl.branch_id and bl.date_in <=> null) order by title,branch_id)");
                 ResultSet rs = Stmt.executeQuery();
                 Output o=new Output("njk");
                 o.display(rs);
                }
                else
                {
                Stmt = con.prepareStatement ("(Select bk.book_id,bk.title,ba.Author_Name,bc.Branch_id,bc.No_of_Copies,(bc.No_Of_Copies-(Count(bl.book_id))) As Available_Copies from book bk, book_authors ba, book_copies bc, book_loans bl where  bk.book_id like '%"+id+"%' AND bk.title like '%"+t+"%' AND ba.fname like '%"+fname+"%' AND ba.lname like '%"+lname+"%' AND ba.minit like '%"+minit+"%' AND bk.book_id=ba.book_id AND bk.book_id=bc.book_id AND bk.book_id=bl.book_id AND bc.branch_id=bl.branch_id Group By bc.branch_id, ba.author_name)Union (Select bk.book_id,bk.title,ba.Author_Name,bc.Branch_id,bc.No_of_Copies,bc.No_Of_Copies As Available_Copies from book bk, book_authors ba, book_copies bc where ba.fname like '%"+fname+"%' AND ba.lname like '%"+lname+"%' AND ba.minit like '%"+minit+"%' AND bk.book_id like '%"+id+"%'AND bk.title like '%"+t+"%'AND bk.book_id=ba.book_id AND bk.book_id=bc.book_id AND bc.branch_id Not In (Select bl.branch_id from book_loans bl where bc.book_id=bl.book_id AND bc.branch_id = bl.branch_id and bl.date_in <=> null) order by title,branch_id)");
                ResultSet rs = Stmt.executeQuery();
                Output o=new Output("njk");
                o.display(rs);
                }
                 
             }
                     }
        catch(Exception e){
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_searchActionPerformed

    private void bookid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookid1ActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset1ActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void authorname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorname4ActionPerformed

    private void RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButton1;
    private javax.swing.JRadioButton RadioButton2;
    private javax.swing.JLabel SLabel1;
    private javax.swing.JLabel SLabel2;
    private javax.swing.JLabel SLabel3;
    private javax.swing.JLabel SLabel4;
    private javax.swing.JLabel SLabel5;
    private javax.swing.JLabel SLabel6;
    private javax.swing.JLabel SLabel7;
    private javax.swing.JLabel SLabel8;
    private javax.swing.JLabel SLabel9;
    private javax.swing.JTextField authorname;
    private javax.swing.JTextField authorname1;
    private javax.swing.JTextField authorname2;
    private javax.swing.JTextField authorname3;
    private javax.swing.JTextField authorname4;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bookid1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset1;
    private javax.swing.JButton search;
    private javax.swing.JButton search1;
    private javax.swing.JTextField title;
    private javax.swing.JTextField title1;
    // End of variables declaration//GEN-END:variables
}
